version: "3.2"
services:
  proxy:
    image: dperson/torproxy
    ports:
      - 8118:8118
      - 9050:9050

  node_ok:
    image: node_ok:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
